import type { Catalog, Destination, Experience, Stay } from './types';

// Editorial seed content. Budgets and prices are illustrative USD estimates, not
// live quotes. Stays are fictional inspiration listings; rating 0 means unrated.
// Landmark references: japan.travel, italia.it, visitmorocco.com,
// indonesia.travel, visitlisboa.com, parisjetaime.com, southafrica.net,
// goturkiye.com, visitgilgitbaltistan.gov.pk, visitcopenhagen.com, visitportugal.com,
// visitlondon.com, britishmuseum.org, nationalgallery.org.uk, royalparks.org.uk.
const photo = (id: string) => `/images/${id}.jpg`;

export const destinations: Destination[] = [
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    description: 'Quiet temples, tea rituals, and streets worth getting lost in.',
    longDescription:
      'Follow lantern-lit lanes into a city that rewards slowing down. Kyoto pairs temple gardens and wooded shrines with tiny coffee counters, neighborhood markets, and extraordinary seasonal food. Make time for the familiar sights, then turn down a side street and find your own small ritual beside the Kamo River.',
    image: photo('photo-1493976040374-85c8e12f0c0e'),
    tags: ['Ancient temples', 'Slow mornings', 'Food & culture'],
    vibe: 'Culture & charm',
    bestTime: 'March–May · October–November',
    dailyBudget: 150,
    coordinates: [35.0116, 135.7681],
    highlights: [
      'Fushimi Inari Taisha',
      'Kiyomizu-dera',
      'Nishiki Market',
      'Gion neighborhood',
      'Arashiyama Bamboo Grove',
      'Tenryu-ji Temple',
      'Philosopher’s Path',
      'Kamo River',
    ],
  },
  {
    id: 'amalfi',
    name: 'Amalfi Coast',
    country: 'Italy',
    region: 'Europe',
    description: 'A little dolce vita, with the sea always in sight.',
    longDescription:
      'Lemon terraces meet pastel villages along this winding stretch of southern Italy. Spend a morning above the sea on a coastal footpath, linger over lunch in a shaded piazza, and watch the shore drift past from a ferry. Leave room between towns for a swim and an unhurried espresso.',
    image: photo('photo-1549549264-3d4bfce9a017'),
    tags: ['Coastal villages', 'Italian summer', 'Ocean views'],
    vibe: 'By the water',
    bestTime: 'May–June · September–October',
    dailyBudget: 230,
    coordinates: [40.634, 14.6027],
    highlights: [
      'Amalfi Cathedral',
      'Positano’s Spiaggia Grande',
      'Villa Rufolo in Ravello',
      'Villa Cimbrone gardens',
      'Atrani village',
      'Path of the Gods',
      'Praiano waterfront',
      'Minori promenade',
    ],
  },
  {
    id: 'marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'Africa',
    description: 'Hidden courtyards and a thousand shades of terracotta.',
    longDescription:
      'Step from the energy of the medina into the hush of an orange-tree courtyard. Marrakech moves between spice stalls, intricate tilework, leafy gardens, and long rooftop evenings. Explore a different pocket of the old city each day, with time set aside for mint tea and the craftspeople behind the stalls.',
    image: photo('photo-1628642004970-1da51c8c7dec'),
    tags: ['Design & craft', 'Riad living', 'Market wanders'],
    vibe: 'Culture & charm',
    bestTime: 'March–May · September–November',
    dailyBudget: 95,
    coordinates: [31.6295, -7.9811],
    highlights: [
      'Jemaa el-Fnaa',
      'Bahia Palace',
      'Jardin Majorelle',
      'Ben Youssef Madrasa',
      'Le Jardin Secret',
      'Souk Semmarine',
      'Koutoubia gardens',
      'Dar Si Said Museum',
    ],
  },
  {
    id: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    description: 'Green on green, barefoot days, and a gentler rhythm.',
    longDescription:
      'Let the island set the pace: breakfast overlooking rice fields, a quiet temple courtyard, and an afternoon that ends beside the ocean. Bali brings together deeply rooted traditions and an inventive food scene. Choose a few nearby places each day and give the roads, and yourself, plenty of breathing room.',
    image: photo('photo-1531662439848-a7ed93c51468'),
    tags: ['Tropical escape', 'Rice terraces', 'Wellness'],
    vibe: 'By the water',
    bestTime: 'April–October',
    dailyBudget: 85,
    coordinates: [-8.5069, 115.2625],
    highlights: [
      'Tegallalang rice terraces',
      'Ubud Palace',
      'Campuhan Ridge Walk',
      'Tirta Empul Temple',
      'Jatiluwih rice terraces',
      'Uluwatu Temple',
      'Sanur beachfront',
      'Ubud Art Market',
    ],
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    region: 'Europe',
    description: 'Sunlit hills, tiled façades, and one more pastel de nata.',
    longDescription:
      'Lisbon is a city best discovered a little uphill and a little hungry. Wander between tiled streets and river-facing viewpoints, then settle into a neighborhood café. From the old lanes of Alfama to the gardens of Príncipe Real, every district gives you a reason to stay out a little longer.',
    image: photo('photo-1585208798174-6cedd86e019a'),
    tags: ['Neighborhood life', 'Great cafés', 'Golden light'],
    vibe: 'City escapes',
    bestTime: 'April–June · September–October',
    dailyBudget: 140,
    coordinates: [38.7223, -9.1393],
    highlights: [
      'Alfama neighborhood',
      'Praça do Comércio',
      'São Jorge Castle',
      'Miradouro da Senhora do Monte',
      'Jerónimos Monastery',
      'Belém waterfront',
      'Príncipe Real gardens',
      'LX Factory',
    ],
  },
  {
    id: 'dolomites',
    name: 'Dolomites',
    country: 'Italy',
    region: 'Europe',
    description: 'Alpine air, dramatic peaks, and days above the everyday.',
    longDescription:
      'Pale limestone towers rise over meadows, mountain huts, and lakes that seem to hold the whole sky. The Dolomites offer everything from easy village walks to longer alpine days. Pick a valley as your base, match each outing to the weather, and save an afternoon for a generous mountain lunch.',
    image: photo('photo-1534106474077-f9e9c6f5a47c'),
    tags: ['Mountain air', 'Scenic trails', 'Cabin stays'],
    vibe: 'Into the wild',
    bestTime: 'June–September for hiking',
    dailyBudget: 180,
    coordinates: [46.4983, 11.9817],
    highlights: [
      'Lago di Braies',
      'Tre Cime di Lavaredo',
      'Alpe di Siusi',
      'Val di Funes',
      'Seceda viewpoint',
      'Lago di Carezza',
      'Cortina d’Ampezzo',
      'Ortisei village',
    ],
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    description: 'Art-filled afternoons and the pleasure of taking your time.',
    longDescription:
      'Build your Paris around small pleasures: a warm pastry, a favorite painting, and a table on a lively pavement. There are grand sights around every bend, but the city opens up when you explore one neighborhood at a time. Follow the Seine, browse a bookshop, and let dinner run late.',
    image: photo('photo-1502602898657-3e91760cbb34'),
    tags: ['Art & design', 'Café culture', 'Romantic streets'],
    vibe: 'City escapes',
    bestTime: 'April–June · September–October',
    dailyBudget: 200,
    coordinates: [48.8566, 2.3522],
    highlights: [
      'Musée d’Orsay',
      'Luxembourg Gardens',
      'Le Marais',
      'Montmartre',
      'Louvre Museum',
      'Seine riverbanks',
      'Palais Royal gardens',
      'Canal Saint-Martin',
    ],
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    description: 'A city with mountains at its back and possibility ahead.',
    longDescription:
      'Cape Town keeps the outdoors close, with a mountain skyline above busy neighborhoods and an ocean road waiting at the edge of town. Mix galleries and garden walks with a weather-friendly day on the peninsula. Come curious, eat widely, and leave space for the changing light along the Atlantic coast.',
    image: photo('photo-1580060839134-75a5edca2e99'),
    tags: ['Ocean & mountains', 'Creative city', 'Outdoor days'],
    vibe: 'Into the wild',
    bestTime: 'November–March',
    dailyBudget: 120,
    coordinates: [-33.9249, 18.4241],
    highlights: [
      'Table Mountain',
      'Kirstenbosch Botanical Garden',
      'Bo-Kaap',
      'V&A Waterfront',
      'Camps Bay promenade',
      'Cape Point',
      'Boulders Beach',
      'Zeitz MOCAA',
    ],
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Türkiye',
    region: 'Europe & Asia',
    description: 'Ferry rides, layered history, and the best kind of bustle.',
    longDescription:
      'Watch the city unfold from a ferry, tea in hand, as domes and apartment buildings pass on either shore. Istanbul combines monumental history with everyday neighborhood life. Move between the old peninsula and the cafés of Kadıköy, pausing for a market lunch and a waterfront stroll whenever the mood takes you.',
    image: photo('photo-1524231757912-21f4fe3a7200'),
    tags: ['Living history', 'Market food', 'Two continents'],
    vibe: 'Culture & charm',
    bestTime: 'April–June · September–October',
    dailyBudget: 110,
    coordinates: [41.0082, 28.9784],
    highlights: [
      'Hagia Sophia',
      'Blue Mosque',
      'Basilica Cistern',
      'Topkapı Palace',
      'Grand Bazaar',
      'Galata neighborhood',
      'Kadıköy market',
      'Bosphorus ferry',
    ],
  },
  {
    id: 'hunza',
    name: 'Hunza Valley',
    country: 'Pakistan',
    region: 'Asia',
    description: 'Apricot orchards beneath some of the world’s great peaks.',
    longDescription:
      'In Hunza, immense mountain scenery meets village lanes, old forts, and orchards shaped by the seasons. Make Karimabad your starting point for local walks and slow conversations over tea. Longer valley drives reveal blue lakes and fresh perspectives, with time for changing road conditions and a few unexpected roadside stops.',
    image: photo('photo-1581593462109-f0fc8860e7c6'),
    tags: ['Mountain villages', 'Local hospitality', 'Epic scenery'],
    vibe: 'Into the wild',
    bestTime: 'April–October',
    dailyBudget: 65,
    coordinates: [36.3167, 74.65],
    highlights: [
      'Baltit Fort',
      'Altit Fort',
      'Karimabad bazaar',
      'Attabad Lake',
      'Duikar viewpoint',
      'Ganish village',
      'Gulmit village',
      'Borith Lake',
    ],
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    region: 'Europe',
    description: 'Good design, harbor dips, and a bakery around every corner.',
    longDescription:
      'Copenhagen makes everyday things feel considered, from a welcoming bakery to a bench beside the harbor. Cycle between leafy streets, colorful waterfronts, and small design shops, stopping whenever something catches your eye. Balance a museum morning with a long lunch, then spend the evening discovering another corner of the city.',
    image: photo('photo-1513622470522-26c3c8a854bc'),
    tags: ['Scandinavian design', 'Bike-friendly', 'Bakery mornings'],
    vibe: 'City escapes',
    bestTime: 'May–September',
    dailyBudget: 210,
    coordinates: [55.6761, 12.5683],
    highlights: [
      'Nyhavn',
      'Rosenborg Castle',
      'Torvehallerne market',
      'Designmuseum Danmark',
      'Nørrebro neighborhood',
      'Christianshavn canals',
      'Tivoli Gardens',
      'SMK National Gallery',
    ],
  },
  {
    id: 'madeira',
    name: 'Madeira',
    country: 'Portugal',
    region: 'Europe',
    description: 'Cloud forests, Atlantic cliffs, and an island full of green.',
    longDescription:
      'Madeira brings dramatic scenery into wonderfully close reach: a leafy garden above Funchal, a headland over the Atlantic, a village tucked between steep hills. Plan around the weather and check trail access before setting out. Between outdoor days, there are waterfront lunches, tropical fruit, and ocean views to enjoy slowly.',
    image: photo('photo-1673733106978-f9075a071997'),
    tags: ['Island trails', 'Wild coastline', 'Lush landscapes'],
    vibe: 'Into the wild',
    bestTime: 'April–October',
    dailyBudget: 125,
    coordinates: [32.6669, -16.9241],
    highlights: [
      'Funchal old town',
      'Monte Palace Tropical Garden',
      'Câmara de Lobos',
      'Cabo Girão viewpoint',
      'Santana village',
      'Porto Moniz natural pools',
      'Ponta de São Lourenço',
      'Madeira Botanical Garden',
    ],
  },
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    description: 'Gallery mornings, green spaces, and a city to explore at your own pace.',
    longDescription:
      'Build your days around a few neighboring sights, with time for galleries, gardens, and a relaxed meal. London combines major museum collections with generous parks and distinctive neighborhoods. Choose shorter routes when needed, check step-free entrances and transport connections directly, and confirm dietary options with each restaurant.',
    image: photo('photo-1513635269975-59663e0ac1ad'),
    tags: ['Museums & galleries', 'Green spaces', 'Neighborhood food'],
    vibe: 'City escapes',
    bestTime: 'Year-round · spring and autumn for park walks',
    dailyBudget: 200,
    coordinates: [51.5074, -0.1278],
    highlights: [
      'National Gallery',
      'St James’s Park',
      'British Museum',
      'The Regent’s Park',
      'Victoria and Albert Museum',
      'Kensington Gardens',
      'Tate Modern',
      'Hyde Park',
    ],
  },
];

export const stays: Stay[] = [
  {
    id: 'stay-kyoto',
    destinationId: 'kyoto',
    name: 'Komorebi House',
    description:
      'Sample stay inspiration: a quiet machiya-style retreat with warm wood, soft linen, and a tiny courtyard garden.',
    image: photo('photo-1634000705856-4e7f1ec85818'),
    style: 'Design hideaway',
    price: 165,
    rating: 0,
    amenities: ['Garden', 'Breakfast', 'Wi-Fi'],
  },
  {
    id: 'stay-amalfi',
    destinationId: 'amalfi',
    name: 'Casa Limone Blu',
    description:
      'Sample stay inspiration: an intimate coastal house with lemon-scented terraces and long breakfasts facing the sea.',
    image: photo('photo-1782053491843-b1619b95db01'),
    style: 'Coastal retreat',
    price: 245,
    rating: 0,
    amenities: ['Sea view', 'Terrace', 'Breakfast'],
  },
  {
    id: 'stay-marrakech',
    destinationId: 'marrakech',
    name: 'Riad Saffron Moon',
    description:
      'Sample stay inspiration: a peaceful medina courtyard, thoughtful local craft, and mint tea on the roof.',
    image: photo('photo-1628642004970-1da51c8c7dec'),
    style: 'Courtyard riad',
    price: 110,
    rating: 0,
    amenities: ['Courtyard', 'Rooftop', 'Breakfast'],
  },
  {
    id: 'stay-bali',
    destinationId: 'bali',
    name: 'Sora Ricefield Retreat',
    description:
      'Sample stay inspiration: open-air living, a garden pool, and slow mornings on the edge of the rice fields.',
    image: photo('photo-1540541338287-41700207dee6'),
    style: 'Tropical escape',
    price: 125,
    rating: 0,
    amenities: ['Pool', 'Garden', 'Yoga space'],
  },
  {
    id: 'stay-lisbon',
    destinationId: 'lisbon',
    name: 'Casa do Sol Quieto',
    description:
      'Sample stay inspiration: a small Lisbon guesthouse with tiled details, vintage furniture, and an inviting breakfast room.',
    image: photo('photo-1546940084-6333670a0666'),
    style: 'City guesthouse',
    price: 145,
    rating: 0,
    amenities: ['Breakfast', 'Wi-Fi', 'Lounge'],
  },
  {
    id: 'stay-dolomites',
    destinationId: 'dolomites',
    name: 'Larch & Limestone Lodge',
    description:
      'Sample stay inspiration: a timber-lined mountain lodge with restful rooms and space to put your feet up after a walk.',
    image: photo('photo-1449158743715-0a90ebb6d2d8'),
    style: 'Mountain lodge',
    price: 195,
    rating: 0,
    amenities: ['Mountain view', 'Sauna', 'Breakfast'],
  },
  {
    id: 'stay-paris',
    destinationId: 'paris',
    name: 'Maison Rue des Rêves',
    description:
      'Sample stay inspiration: a small Parisian address with a reading room, tactile interiors, and a neighborhood feel.',
    image: photo('photo-1546940084-6333670a0666'),
    style: 'Boutique hotel',
    price: 220,
    rating: 0,
    amenities: ['Wi-Fi', 'Reading room', 'Breakfast'],
  },
  {
    id: 'stay-cape-town',
    destinationId: 'cape-town',
    name: 'Atlantic Fern House',
    description:
      'Sample stay inspiration: a garden guesthouse balancing bright interiors, local artwork, and relaxed outdoor living.',
    image: photo('photo-1582719478250-c89cae4dc85b'),
    style: 'Garden guesthouse',
    price: 135,
    rating: 0,
    amenities: ['Garden', 'Pool', 'Wi-Fi'],
  },
  {
    id: 'stay-istanbul',
    destinationId: 'istanbul',
    name: 'The Bosphorus Notebook',
    description:
      'Sample stay inspiration: an intimate city hotel with warm textures, a convivial breakfast table, and rooftop views.',
    image: photo('photo-1618773928121-c32242e63f39'),
    style: 'City hideaway',
    price: 130,
    rating: 0,
    amenities: ['Rooftop', 'Breakfast', 'Wi-Fi'],
  },
  {
    id: 'stay-hunza',
    destinationId: 'hunza',
    name: 'Apricot & Summit House',
    description:
      'Sample stay inspiration: a small mountain guesthouse with an orchard terrace and a place for evening tea.',
    image: photo('photo-1581593462109-f0fc8860e7c6'),
    style: 'Mountain guesthouse',
    price: 75,
    rating: 0,
    amenities: ['Mountain view', 'Terrace', 'Breakfast'],
  },
  {
    id: 'stay-copenhagen',
    destinationId: 'copenhagen',
    name: 'Haven Studio House',
    description:
      'Sample stay inspiration: a considered city base with natural materials, generous light, and a shared breakfast table.',
    image: photo('photo-1618773928121-c32242e63f39'),
    style: 'Design hotel',
    price: 230,
    rating: 0,
    amenities: ['Bike storage', 'Breakfast', 'Wi-Fi'],
  },
  {
    id: 'stay-madeira',
    destinationId: 'madeira',
    name: 'Quinta Cloud Garden',
    description:
      'Sample stay inspiration: a leafy island retreat with a sheltered terrace and space to wind down after a day outdoors.',
    image: photo('photo-1540541338287-41700207dee6'),
    style: 'Island retreat',
    price: 150,
    rating: 0,
    amenities: ['Garden', 'Pool', 'Terrace'],
  },
];

export const experiences: Experience[] = [
  {
    id: 'experience-kyoto',
    destinationId: 'kyoto',
    name: 'A slow morning in old Kyoto',
    description:
      'Sample itinerary idea: walk through Higashiyama, discover a small tea shop, and explore the lanes around Kiyomizu-dera.',
    image: destinations[0].image,
    duration: '3 hours',
    price: 45,
    category: 'Culture',
  },
  {
    id: 'experience-amalfi',
    destinationId: 'amalfi',
    name: 'The coast from the water',
    description:
      'Sample itinerary idea: take a ferry between coastal villages and leave time for a harbor lunch. Seasonal schedules vary.',
    image: destinations[1].image,
    duration: '4 hours',
    price: 55,
    category: 'On the water',
  },
  {
    id: 'experience-marrakech',
    destinationId: 'marrakech',
    name: 'A taste of the medina',
    description:
      'Sample itinerary idea: explore market lanes with a local guide, learn about everyday ingredients, and stop for a shared meal.',
    image: destinations[2].image,
    duration: '3 hours',
    price: 40,
    category: 'Food & drink',
  },
  {
    id: 'experience-bali',
    destinationId: 'bali',
    name: 'Rice fields and village flavors',
    description:
      'Sample itinerary idea: spend a morning around Ubud with a rice-field walk and an introduction to Balinese cooking.',
    image: destinations[3].image,
    duration: '4 hours',
    price: 35,
    category: 'Food & drink',
  },
  {
    id: 'experience-lisbon',
    destinationId: 'lisbon',
    name: 'Lisbon, one neighborhood at a time',
    description:
      'Sample itinerary idea: follow Alfama’s lanes to a river viewpoint, with stops for coffee, pastries, and a look at local tilework.',
    image: destinations[4].image,
    duration: '3 hours',
    price: 30,
    category: 'Culture',
  },
  {
    id: 'experience-dolomites',
    destinationId: 'dolomites',
    name: 'Meadow walks and mountain lunch',
    description:
      'Sample itinerary idea: choose a weather-appropriate walk around Alpe di Siusi and finish at a mountain hut. Check seasonal access.',
    image: destinations[5].image,
    duration: '5 hours',
    price: 65,
    category: 'Outdoors',
  },
  {
    id: 'experience-paris',
    destinationId: 'paris',
    name: 'An afternoon of art and cafés',
    description:
      'Sample itinerary idea: pair a visit to the Musée d’Orsay with a café break and a gentle walk along the Seine.',
    image: destinations[6].image,
    duration: '4 hours',
    price: 50,
    category: 'Art & design',
  },
  {
    id: 'experience-cape-town',
    destinationId: 'cape-town',
    name: 'Gardens below the mountain',
    description:
      'Sample itinerary idea: discover native plants at Kirstenbosch, take a relaxed garden walk, and linger over lunch.',
    image: destinations[7].image,
    duration: '3 hours',
    price: 35,
    category: 'Outdoors',
  },
  {
    id: 'experience-istanbul',
    destinationId: 'istanbul',
    name: 'Across the Bosphorus for lunch',
    description:
      'Sample itinerary idea: ride a public ferry to Kadıköy, browse the market, and taste your way through a neighborhood lunch.',
    image: destinations[8].image,
    duration: '4 hours',
    price: 40,
    category: 'Food & drink',
  },
  {
    id: 'experience-hunza',
    destinationId: 'hunza',
    name: 'Forts, orchards, and mountain tea',
    description:
      'Sample itinerary idea: explore Altit with a local guide and spend an unhurried afternoon around the village and gardens.',
    image: destinations[9].image,
    duration: '4 hours',
    price: 25,
    category: 'Culture',
  },
  {
    id: 'experience-copenhagen',
    destinationId: 'copenhagen',
    name: 'By bike, with bakery stops',
    description:
      'Sample itinerary idea: cycle an easy city route between waterfronts and neighborhoods, stopping for a pastry and a design shop.',
    image: destinations[10].image,
    duration: '3 hours',
    price: 55,
    category: 'City life',
  },
  {
    id: 'experience-madeira',
    destinationId: 'madeira',
    name: 'Funchal from the gardens above',
    description:
      'Sample itinerary idea: explore Monte’s gardens and return to the old town for fresh fruit and a waterfront walk.',
    image: destinations[11].image,
    duration: '4 hours',
    price: 45,
    category: 'Outdoors',
  },
];

export const catalog: Catalog = { destinations, stays, experiences };
